webtalk_init -webtalk_dir D:/Jake_Gu/UT Austin/GitHub/High-Speed-Project/src/Booth_RA_Mul/Booth_RA_Mul/Booth_RA_Mul.sim/sim_1/impl/timing/xsim/xsim.dir/Booth_RA_Mul_tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 11 21:00:09 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "166c82fa3b0a5fd7804c4a70315997a1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aa8bda4a10194f5a96c109210d38ec51" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "9" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1426 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "273 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "4449" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "612" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.61_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "198236_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1144730858 -regid "" -xml D:/Jake_Gu/UT Austin/GitHub/High-Speed-Project/src/Booth_RA_Mul/Booth_RA_Mul/Booth_RA_Mul.sim/sim_1/impl/timing/xsim/xsim.dir/Booth_RA_Mul_tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/Jake_Gu/UT Austin/GitHub/High-Speed-Project/src/Booth_RA_Mul/Booth_RA_Mul/Booth_RA_Mul.sim/sim_1/impl/timing/xsim/xsim.dir/Booth_RA_Mul_tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/Jake_Gu/UT Austin/GitHub/High-Speed-Project/src/Booth_RA_Mul/Booth_RA_Mul/Booth_RA_Mul.sim/sim_1/impl/timing/xsim/xsim.dir/Booth_RA_Mul_tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
